# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Ashore Detroit"
description: > # this means to ignore newlines until "email:"
   The Detroit watersports and lifestyle blog

email: detroit@ashore.me
#blog logo
logo: "/assets/images/ashore_detroit_logo.png"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Ashore Detroit'
author: 'Brian Mulloy'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://detroit.ashore.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@ashoredetroit'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ashoredetroit
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/ashoredetroit
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/ashore-media/detroit
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
